Lapin-Learn/mobile

- app/(tabs)/(map)/index.tsx
- app/(tabs)/profile/index.tsx
- app/_layout.tsx
- app/index.tsx
- app/update-profile.tsx
- components/navigation/AppStack.tsx
- hooks/react-query/useAuth.ts
- hooks/react-query/useUser.ts
- hooks/zustand/useAuthStore.ts
- lib/interfaces.ts
- package-lock.json
- providers/auth.tsx
- services/auth.ts
- services/httpRequests.ts
- services/index.ts
- services/user.ts
uncomment TODO in useUser.ts file when update user profile
> fix(lap-181, lap-182, lap-183): fix bug access map without log in

- app/edit-profile/index.tsx
- components/molecules/ControllerInput.tsx
- components/molecules/CustomTextInput.tsx
- components/molecules/SelectInput.tsx
- hooks/react-query/useUser.ts
- hooks/useFormInput.tsx
- Add useFormInput hook
- Refactor ControllerInput
> refactor(lap-264): controller input

- hooks/react-query/useAuth.ts
- services/axios/auth.ts
Make sure no account with test email in database and firebase
Test:
log in with provider at first
check firebase whether the pwd account is also created with the same email
use forgot password to change password of that email
log in with email and new password again
> refactor(lap-343): change to call api before login with provider

- hooks/react-query/useAuth.ts
- services/axios/auth.ts
- check again the sign in and sign up flow
- check it should have the refresh token after sign in, sign up
> refactor(lap-343): change to only call provider api

- app/exercise/[exerciseId]/[questionTypeId]/index.tsx
- app/lesson/[lessonId].tsx
- components/organisms/exercise/AnswerModal.tsx
- components/organisms/exercise/QuestionTemplate.tsx
- components/organisms/exercise/answer-input/MultipleChoice.tsx
- components/organisms/exercise/answer-input/matching/Matching.tsx
- style(lap-357): center lesson card
- fix(lap-357): fix term 'no question' is displayed before showing question
- style(lap-357): make answer options not be hidden by checking button
_These pictures above are in inspect mode so style can be different a little bit_
> LAP-357: Check button cover the choices

- app/edit-profile/index.tsx
- app/update-profile.tsx
- components/molecules/form-input/CustomTextInput.tsx
- components/molecules/form-input/SelectInput.tsx
- components/primitives/select/select.tsx
- hooks/useFormInput.tsx
- Change the text color of gender placeholder to gray
> style(lap-347): gender placeholder text color

- app/(tabs)/mission/index.tsx
- app/auth/(forgot-password)/forgot-password.tsx
- app/auth/(forgot-password)/reset-password.tsx
- app/auth/(forgot-password)/verify.tsx
- app/index.tsx
- components/molecules/NavigationBar.tsx
- components/organisms/exercise/QuestionTemplate.tsx
- components/templates/PlatformView.tsx
- constants/GlobalStyles.ts
- locales/en/auth.json
- locales/vi/auth.json
- services/axios/auth.ts
- services/axios/user.ts
Update back to previous otp input when user delete input of current otp input
> fix(lap-379): update verify flow when user enter invalid otp

- app/(tabs)/mission/index.tsx
- app/auth/(forgot-password)/reset-password.tsx
- app/auth/sign-up.tsx
- app/edit-profile/change-password/index.tsx
- app/exercise/[exerciseId]/index.tsx
- components/molecules/ControllerInput.tsx
- components/molecules/NavigationBar.tsx
- components/organisms/lesson/LessonResult.tsx
- constants/GlobalStyles.ts
- global.css
- hooks/react-query/useAuth.ts
- lib/constants.ts
- locales/en/auth.json
- locales/vi/auth.json
> [Auth] Error messages aren't in readable format and [Auth] Don't clear error of confirm password when update password

- android/app/build.gradle
- android/app/src/main/java/com/datn/lapinlearn/LapinLearnWidget.kt
- android/app/src/main/res/values-vi/strings.xml
- android/app/src/main/res/values/strings.xml
- lib/utils.ts
> fix(lap-406): change widget no data style

- components/molecules/milestone/MissionMilestone.tsx
- hooks/react-query/useAuth.ts
- package-lock.json
- package.json
- services/axios/auth.ts
[screen-capture (5).webm](https://github.com/user-attachments/assets/7ae67a82-a899-40f6-adca-f98c7740d163)
> fix(lap-380): fix sign in w gg get previous acc

- app/(tabs)/(map)/index.tsx
- components/molecules/exercise/ScrollableReadingContainer.tsx
- components/molecules/milestone/MissionMilestone.tsx
- components/molecules/milestone/NewMilestone.tsx
- components/molecules/track-bar/TrackBar.tsx
- components/organisms/exercise/QuestionTemplate.tsx
- components/organisms/lesson/LessonResult.tsx
- hooks/react-query/useDailyLesson.ts
[screen-capture (6).webm](https://github.com/user-attachments/assets/91f4467c-c419-446f-8ea6-9abcfc00da10)
> Modal covers matching answers and Resizable question card

- app/auth/sign-up.tsx
- app/update-profile.tsx
- components/molecules/ControllerInput.tsx
- components/molecules/ShopModal.tsx
- locales/en/validation.json
- locales/vi/validation.json
- Fix loop when incomplete update profile screen
- Fix warn when reset state
> fix(lap-439): Fix warn when reset state

- app/(tabs)/profile/index.tsx
- app/exercise/[exerciseId]/index.tsx
- app/lesson/explanation/index.tsx
- app/streak/index.tsx
- components/molecules/MatchingItem.tsx
- components/molecules/exercise/ScrollableReadingContainer.tsx
- components/organisms/exercise/QuestionCard.tsx
- components/organisms/exercise/QuestionTemplate.tsx
- components/organisms/exercise/answer-input/Matching.tsx
- components/organisms/lesson/LessonResult.tsx
- components/primitives/select/select.tsx
- components/ui/Progress.tsx
- components/ui/RadioGroup.tsx
- components/ui/Select.tsx
- lib/types/questions.ts
- package-lock.json
- Matching question type, introduce new props `direction` and `textColumnKey` to identify which column should be selectable and whether position is before or after.
- Change the placeholder color of Select component
- Some small UI bugs:
- Increase the size of the back button
- Decrease the font in reading paragraph
-  Add questionNo/totalQuestion
> style(matching): select component, matching question, etc.

- .github/workflows/release-artifact.yml
- app/(tabs)/profile/index.tsx
- app/exercise/[exerciseId]/index.tsx
- app/lesson/explanation/index.tsx
- app/streak/index.tsx
- components/molecules/MatchingItem.tsx
- components/molecules/exercise/ScrollableReadingContainer.tsx
- components/organisms/exercise/QuestionCard.tsx
- components/organisms/exercise/QuestionTemplate.tsx
- components/organisms/exercise/answer-input/Matching.tsx
- components/organisms/lesson/LessonResult.tsx
- components/primitives/select/select.tsx
- components/ui/Progress.tsx
- components/ui/RadioGroup.tsx
- components/ui/Select.tsx
- lib/types/questions.ts
- package-lock.json
- Matching question type, introduce new props direction and textColumnKey to identify which column should be selectable and whether position is before or after.
- Change the placeholder color of Select component
- Some small UI bugs:
- Increase the size of the back button
- Decrease the font in reading paragraph
- Add questionNo/totalQuestion
> style: matching question 

- components/molecules/MatchingItem.tsx
- components/organisms/exercise/answer-input/Matching.tsx
Fix this bug reported by my fr :">
Solution: change all logic columnA, columnB to textColumnKey and selectColumnKey
> fix: matching answer record not working

- .gitignore
- android/app/build.gradle
- app.json
- app/(tabs)/profile/index.tsx
- components/organisms/exercise/answer-input/Matching.tsx
- components/organisms/exercise/answer-input/speaking/Speaking.tsx
- components/organisms/exercise/answer-input/speaking/helpers.ts
- ios/LapinLearn/Info.plist
* fix: matching logic and layout pronounciation
* style: padding profile
> fix: matching logic and pronounciation UI

- app/auth/sign-in.tsx
- app/exercise/[exerciseId]/[questionTypeId]/index.tsx
- app/exercise/[exerciseId]/index.tsx
- components/molecules/LessonCard.tsx
- components/molecules/NavigationBar.tsx
- components/molecules/exercise/ChoiceButton.tsx
- components/molecules/exercise/ChoiceCheckBox.tsx
- components/molecules/exercise/ChoiceRadio.tsx
- components/molecules/map/SkillCard.tsx
- components/molecules/map/Welcome.tsx
- components/molecules/mission/MissionSection.tsx
- components/organisms/exercise/QuestionTemplate.tsx
- components/organisms/exercise/answer-input/MultipleChoice.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/FillInTheBlankInput.tsx
- components/organisms/lesson/LessonResult.tsx
- components/organisms/question-card/index.tsx
- components/ui/Button.tsx
- components/ui/Progress.tsx
- hooks/react-query/useAuth.ts
- hooks/react-query/useDailyLesson.ts
- ios/LapinLearn/Info.plist
- lib/types/question-style.ts
- lib/utils/question-decoration.ts
- Different decoration multiple choice render
- Adjust font size, welcome, lesson card
> style: multiple choice

- app.json
- app/(tabs)/profile/index.tsx
- components/molecules/avatar.tsx
- components/molecules/exercise/ChoiceButton.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/FillInTheBlank.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/FillInTheBlankInput.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/TypeRendering.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/helper.ts
- hooks/react-query/useUser.ts
- services/axios/bucket.ts
- services/axios/user.ts
- services/index.ts
Fix render index of each blank
Separate the function checking answer to adapt multiple checking correctness
> fix(LAP-774 LAP-778): logic handle fill in the blanks, image issue

- .github/workflows/release-artifact.yml
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- app.json
- app/(tabs)/profile/index.tsx
- components/molecules/avatar.tsx
- components/molecules/exercise/ChoiceButton.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/FillInTheBlank.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/FillInTheBlankInput.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/TypeRendering.tsx
- components/organisms/exercise/answer-input/fill-in-the-blank/helper.ts
- hooks/react-query/useUser.ts
- ios/LapinLearn/Info.plist
- services/axios/bucket.ts
- services/axios/user.ts
- services/index.ts
- Fill in the blank indexing logic
- Upload avatar smoother
- Request permissions android
- Add workflow dispatch
> fix: fill in the blanks and enhance upload avatar

- app/(tabs)/profile/index.tsx
- app/edit-profile/index.tsx
- components/molecules/ControllerInput.tsx
- components/molecules/form-input/CustomDateInput.tsx
- components/organisms/modals/DeleteAccountModal.tsx
- hooks/react-query/useAuth.ts
- hooks/useFormInput.tsx
- change the position of delete account dialog
- fix bug update profile:
- Default dob to undefined, not today
- Change default gender to undefined
- Reset state after update profile successfully
> fix(LAP-827): delete account dialog, edit profile
